project_id = "nukus-go-db"

[functions.send-signup-otp]
verify_jwt = false

[functions.verify-signup-otp]
verify_jwt = false

[functions.reset-password-with-otp]
verify_jwt = false

[functions.telerivet-sms-hook]
verify_jwt = false
