export const routes = [
  { path: "/", scope: "public" },
  { path: "/login", scope: "public" },
  { path: "/register", scope: "public" },
  { path: "/client/home", scope: "client" },
  { path: "/client/taxi", scope: "client" },
  { path: "/client/delivery", scope: "client" },
  { path: "/client/freight", scope: "client" },
  { path: "/client/inter-provincial", scope: "client" },
  { path: "/client/inter-district", scope: "client" },
  { path: "/driver/home", scope: "driver" },
  { path: "/driver/orders", scope: "driver" },
  { path: "/driver/wallet", scope: "driver" },
  { path: "/driver/profile", scope: "driver" },
];
