import React, { useMemo, useState } from "react";
import { Card, InputNumber, Select, Divider } from "antd";
import { CalculatorOutlined } from "@ant-design/icons";
import { FX } from "../../services/priceUtils";
import { useAutoMarketI18n } from "../../utils/useAutoMarketI18n";

export default function VikupCalculator({ car, vikup }) {
 const { am } = useAutoMarketI18n();
 const MONTHS_OPTIONS=["6","12","18","24","36","48","60"].map(x=>({ value:x, label:`${x} ${am("serviceBook.monthShort", "oy")}` }));
 const carPrice=useMemo(()=>{ const p=Number(car?.price||0); const cur=(car?.currency||"UZS").toUpperCase(); if(cur==="USD") return p; return Math.round(p/(FX.USD_UZS||12500)); },[car]);
 const [initial,setInitial]=useState(Number(vikup?.initial_payment||2000)); const [monthly,setMonthly]=useState(Number(vikup?.monthly_payment||300)); const [months,setMonths]=useState(String(vikup?.duration_months||12)); const [interest,setInterest]=useState(Number(vikup?.interest_rate||0));
 const monthsNum=Number(months);
 const result=useMemo(()=>{ const base=initial+monthly*monthsNum; const yearlyRate=interest/100; const monthRate=yearlyRate/12; let totalWithInt=base; if(interest>0&&monthRate>0){ const annuity=monthly*monthsNum; const interestTotal=(carPrice-initial)*monthRate*monthsNum*(1+monthRate*monthsNum/2); totalWithInt=initial+annuity+interestTotal; } const overpay=totalWithInt-carPrice; const overpayPct=carPrice>0?Math.round((overpay/carPrice)*100):0; return { total:Math.round(totalWithInt), overpay:Math.round(overpay), overpayPct, monthlyEffective:Math.round(totalWithInt/Math.max(1,monthsNum))}; },[initial,monthly,monthsNum,interest,carPrice]);
 const fmt=(n)=>Number(n||0).toLocaleString("uz-UZ");
 return <Card style={{ borderRadius:18, border:"1px solid #fde68a", background:"#fffbeb" }} styles={{ body: { padding:16 } }}><div style={{ display:"flex", gap:10, alignItems:"center", marginBottom:14 }}><div style={{ width:40,height:40,borderRadius:14,background:"linear-gradient(135deg,#f59e0b,#d97706)",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",boxShadow:"0 8px 20px rgba(217,119,6,.3)" }}><CalculatorOutlined /></div><div><div style={{ fontWeight:900,color:"#0f172a" }}>{am("autoExtra.vikupCalc")}</div><div style={{ fontSize:12,color:"#92400e" }}>{am("autoExtra.monthlyCalc")}</div></div></div>{carPrice>0&&<div style={{ fontSize:12,color:"#92400e",marginBottom:12,fontWeight:700 }}>{am("autoExtra.carPrice")}: ${fmt(carPrice)}</div>}<div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:10 }}><div><div style={{ fontSize:12,color:"#64748b",fontWeight:700,marginBottom:4 }}>{am("autoExtra.initialPayment")} ($)</div><InputNumber value={initial} onChange={(v)=>setInitial(Number(v||0))} style={{ width:"100%" }} min={0} placeholder="2000" /></div><div><div style={{ fontSize:12,color:"#64748b",fontWeight:700,marginBottom:4 }}>{am("autoExtra.monthlyPayment")} ($)</div><InputNumber value={monthly} onChange={(v)=>setMonthly(Number(v||0))} style={{ width:"100%" }} min={0} placeholder="300" /></div><div><div style={{ fontSize:12,color:"#64748b",fontWeight:700,marginBottom:4 }}>{am("autoExtra.term")}</div><Select value={months} onChange={setMonths} style={{ width:"100%" }} options={MONTHS_OPTIONS} /></div><div><div style={{ fontSize:12,color:"#64748b",fontWeight:700,marginBottom:4 }}>{am("autoExtra.annualRate")}</div><InputNumber value={interest} onChange={(v)=>setInterest(Number(v||0))} style={{ width:"100%" }} min={0} max={100} placeholder="0" /></div></div><Divider style={{ margin:"14px 0" }} /><div style={{ background:"linear-gradient(135deg,#111,#333)", borderRadius:14, padding:"14px 16px", color:"#fff" }}><div style={{ display:"flex", justifyContent:"space-between", marginBottom:8 }}><span style={{ fontSize:12, opacity:.8 }}>{am("autoExtra.totalPayment")}:</span><span style={{ fontWeight:900, color:"#fde68a", fontSize:16 }}>${fmt(result.total)}</span></div><div style={{ display:"flex", justifyContent:"space-between", marginBottom:8 }}><span style={{ fontSize:12, opacity:.8 }}>{am("autoExtra.avgMonthly")}:</span><span style={{ fontWeight:700, color:"#86efac" }}>${fmt(result.monthlyEffective)}/oy</span></div>{result.overpay>0?<div style={{ display:"flex", justifyContent:"space-between" }}><span style={{ fontSize:12, opacity:.8 }}>{am("autoExtra.overpay")}:</span><span style={{ fontWeight:700, color:"#fca5a5" }}>+${fmt(result.overpay)} ({result.overpayPct}%)</span></div>:<div style={{ fontSize:12, color:"#86efac", fontWeight:700 }}>✅ {am("autoExtra.interestFree")}</div>}</div></Card>;
 }
