apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unigo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "200"
spec:
  tls:
  - hosts: [api.unigo.uz]
    secretName: unigo-tls
  rules:
  - host: api.unigo.uz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port: { number: 80 }
