
export const ORDER_STATES = [
"CREATED",
"SEARCHING_DRIVER",
"DRIVER_OFFERED",
"DRIVER_ACCEPTED",
"DRIVER_ARRIVED",
"RIDE_STARTED",
"RIDE_COMPLETED",
"PAYMENT_PENDING",
"PAYMENT_COMPLETED"
]

export function isValidTransition(current,next){

 const map={

  CREATED:["SEARCHING_DRIVER"],

  SEARCHING_DRIVER:["DRIVER_OFFERED"],

  DRIVER_OFFERED:["DRIVER_ACCEPTED"],

  DRIVER_ACCEPTED:["DRIVER_ARRIVED"],

  DRIVER_ARRIVED:["RIDE_STARTED"],

  RIDE_STARTED:["RIDE_COMPLETED"],

  RIDE_COMPLETED:["PAYMENT_PENDING"],

  PAYMENT_PENDING:["PAYMENT_COMPLETED"]

 }

 return (map[current]||[]).includes(next)

}
