export const initialFormValues = {
  transport_type: "light_car",
  seat_count: 4,
  requested_max_freight_weight_kg: 100,
  requested_payload_volume_m3: null,
  first_name: "",
  last_name: "",
  father_name: "",
  phone: "",
  passport_number: "",
  vehicle_brand: "",
  vehicle_model: "",
  vehicle_year: null,
  vehicle_plate: "",
  vehicle_color: "",
  driver_license_number: "",
  tech_passport_number: "",
};
