input {
  beats { port => 5044 }
  tcp   { port => 5000; codec => json }
}

filter {
  if [service] {
    mutate { add_tag => [ "unigo", "%{service}" ] }
  }
  date {
    match => ["ts", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "unigo-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
